name: Tag and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**.js'

jobs:
  tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish NPM Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node.js 20
        uses: actions/setup-node@master
        with:
          version: 20.x
      - name: npm ci
        run: npm ci
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}