name: Tag and Publish

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**.js'

jobs:
  tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  publish:
    name: Publish NPM Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node.js 22
        uses: actions/setup-node@master
        with:
          version: 22.x
      - name: npm ci
        run: npm ci
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}